### ISSUE TITLE
remove requirement for nostr-zap-target id

### ISSUE THREAD

**Issue by SamSamskies** [SamSamskies/nostr-zap#5]
nostr-zap-target id isn't necessary. this limits the user to only having one zap target on their page. can query by the data-npub attribute instead.

**Comment by erskingardner** [comment]
Yes! I was about to add this to nostr.how and listr but realized that I can't because I have multiple buttons on the page.

**Comment by SamSamskies** [comment]
resolved with v0.5.0

**Comment by erskingardner** [comment]
Legend! Thanks.
